##### Terminal / Color Fix (REQUIRED) #####
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Use Ctrl+a instead of Ctrl+b (easier)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Mouse support (scroll + click panes)
set -g mouse on

# Faster escape
set -sg escape-time 0

# Pane navigation with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind ] split-window -h -c "#{pane_current_path}"
bind [ split-window -v -c "#{pane_current_path}"
# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"
bind c new-window -c  "#{pane_current_path}"

# ---- Tokyo Night Color Palette ----
set -g @tn_bg "#1a1b26"
set -g @tn_fg "#c0caf5"
set -g @tn_blue "#7aa2f7"
set -g @tn_cyan "#7dcfff"
set -g @tn_purple "#bb9af7"
set -g @tn_gray "#565f89"


# ---- Status Bar ----
set -g status on
set -g status-interval 2
set -g status-style "bg=#{@tn_bg},fg=#{@tn_fg}"


# Left: session name
set -g status-left-length 40
set -g status-left "#[fg=#{@tn_blue},bold]  #S "


# Right: date & time
set -g status-right-length 100
set -g status-right "#[fg=#{@tn_gray}] %Y-%m-%d #[fg=#{@tn_purple}] %H:%M "

# Window list
setw -g window-status-style "bg=#{@tn_bg},fg=#{@tn_gray}"
setw -g window-status-current-style "bg=#{@tn_bg},fg=#{@tn_cyan},bold"

setw -g window-status-format "  #I:#W  "
setw -g window-status-current-format "  #I:#W  "



# Pane borders
set -g pane-border-style "fg=#{@tn_gray}"
set -g pane-active-border-style "fg=#{@tn_blue}"



# Messages
set -g message-style "bg=#{@tn_bg},fg=#{@tn_cyan}"
set -g message-command-style "bg=#{@tn_bg},fg=#{@tn_purple}"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-hook-pre-restore-pane-processes 'test -s ~/.local/share/tmux/resurrect/last && tmux switch-client -n && tmux kill-session -t=0'
set -g @continuum-restore 'on'
set -g @resurrect-strategy-nvim 'session'
set-hook -g session-closed 'if-shell "[ #{session_name} != 0 ]" "run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh"'
set-hook -g client-detached 'run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh'
run '~/.tmux/plugins/tpm/tpm'
